name 'formatron_beats'
version '0.1.0'
description 'Formatron Beats cookbook'
source_url 'https://github.com/formatron/beats-cookbook'
issues_url 'https://github.com/formatron/beats-cookbook/issues'
supports 'ubuntu'
depends 'apt'
depends 'formatron_elasticsearch'
