name 'formatron_beats'
version '0.1.1'
description 'Formatron Beats cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/beats-cookbook'
issues_url 'https://github.com/formatron/beats-cookbook/issues'
supports 'ubuntu'
depends 'apt'
depends 'formatron_elasticsearch'
